version: "3.7"

x-deploy: &template-deploy
  replicas: 1
  restart_policy:
      condition: any
  update_config:
      parallelism: 1
      delay: 10s

services:
  adminer:
    image: adminer
    networks:
      - "monitoring-network"
    ports:
      - "8090:8080"
    deploy: *template-deploy
  demo_django:
      image: treborbrz/demo_django
      networks:
          - "monitoring-network"
      ports:
          - "8000:8000"
      volumes:
          - ./demo_django:/app/demo_django
      env_file: 
          ./envs/common.env
      deploy: *template-deploy
      entrypoint: /app/docker-entrypoint.sh

networks:
    monitoring-network:
        external: True
