# Generated by Django 3.0.7 on 2020-06-03 22:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_consolidadesale_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='consolidadesale',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.Stores'),
        ),
    ]
