# Generated by Django 3.0.7 on 2020-06-04 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
