# Generated by Django 3.0.7 on 2020-06-04 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_auto_20200604_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consolidadesale',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.RenameModel(
            old_name='Stores',
            new_name='Store',
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('product', models.ManyToManyField(to='stores.Product')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.Store')),
            ],
            options={
                'ordering': ['quantity'],
            },
        ),
    ]
