# Generated by Django 3.0.7 on 2020-06-04 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_auto_20200604_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='state',
        ),
    ]
