# Generated by Django 3.0.7 on 2020-06-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_sale_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
